
import React from 'react';
import styled, { css } from 'react-emotion';


const iconMap = {
  pause: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTEyIiBoZWlnaHQ9IjExMiIgdmlld0JveD0iMCAwIDExMiAxMTIiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PHRpdGxlPlBhdXNlPC90aXRsZT48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGQ9Ik0yLjkyNyA1LjI2OGg5OS45MDJ2OTkuOTAySDIuOTI2eiIvPjxjaXJjbGUgZmlsbD0iIzE0MUI0RCIgb3BhY2l0eT0iLjYiIGN4PSI1NiIgY3k9IjU2IiByPSI1NiIvPjxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDM5IDMxKSIgZmlsbD0iI0VGRUZGNCI+PHJlY3Qgd2lkdGg9IjEwIiBoZWlnaHQ9IjUwIiByeD0iNSIvPjxyZWN0IHg9IjI0LjE5NSIgd2lkdGg9IjEwIiBoZWlnaHQ9IjUwIiByeD0iNSIvPjwvZz48L2c+PC9zdmc+',
  play: 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMzAiIGhlaWdodD0iMzAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj48cGF0aCBkPSJNMTUgMzBDNi43MyAzMCAwIDIzLjI3IDAgMTVTNi43MyAwIDE1IDBzMTUgNi43MyAxNSAxNS02LjczIDE1LTE1IDE1eiIgZmlsbD0iIzE0MUI0RCIgb3BhY2l0eT0iLjYiLz48cGF0aCBkPSJNMTUgMjljNy43MTggMCAxNC02LjI4MiAxNC0xNFMyMi43MTggMSAxNSAxIDEgNy4yODIgMSAxNXM2LjI4MiAxNCAxNCAxNHptMCAxQzYuNzMgMzAgMCAyMy4yNyAwIDE1UzYuNzMgMCAxNSAwczE1IDYuNzMgMTUgMTUtNi43MyAxNS0xNSAxNXoiIGZpbGw9IiNDQkNBRDUiIGZpbGwtcnVsZT0ibm9uemVybyIvPjxwYXRoIGQ9Ik0yMC42ODEgMTUuNzRsLTcuMjY5IDUuMDMyYS45LjkgMCAwIDEtMS40MTItLjc0VjkuOTY4YS45LjkgMCAwIDEgMS40MTItLjc0bDcuMjcgNS4wMzJhLjkuOSAwIDAgMSAwIDEuNDh6IiBmaWxsPSIjRkZGIi8+PC9nPjwvc3ZnPg=='
};


const baseIcon = ({ className }) => (
  <div className={className}></div>
);

const Icon = styled(baseIcon)(props => ({
  backgroundImage: `url(${iconMap[props.type]})`,
  backgroundSize: 'contain',
  width: '30px',
  height: '30px'
}));

export default Icon;
